---
title: "Gov 50 Final Project"
author: "Arjun Akwei"
description: "The Effect of EU Membership On National Liberalization"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring how determining whether membership in a liberal international organization such as the EU has caused new member countries to liberalize politically in a significant way. Between 1990 and 2005 several former Soviet sphere countries were making the decision of whether or not to join the EU, and many EU members and allies hoped that their joining would promote democratization and liberalization. I am curious to assess whether such an impact was seen. 

My plan is to curate a sample of countries from the "Eastern Bloc" that joined the EU in the same year, and map years spent in EU against their annual scores on the UN's Human Freedom Index. I would then conduct a difference in difference analysis using a sample of countries from that bloc that chose not to join the EU to determine the treatment effect of EU membership.

**Sample of Eastern Bloc countries now in EU**  
- Poland 2004  
- Czech Republic 2004  
- Estonia 2004  
- Hungary 2004  
- Slovakia 2004  
**Sample of Eastern bloc countries NOT in EU**  
- Albania  
- Moldova  
- Ukraine  
- Belarus  
- Georgia  

## Research Proposal
In this study, I hope to explore whether membership in a liberal international organization such as the EU has caused new member countries to liberalize politically in a significant way. I hypothesize, new requirements for member liberalization, facilitated integration into the global economy, and direct support from the organization itself, among other factors, cause member organizations to liberalize and develop as democracies at rates far faster than they would have without joining. The explanatory variable in this case is time spent as a member in a liberal international organization (specifically in this case the EU), something measured in years since being granted membership (in 2004). A separate set of countries from the same region that did NOT join the EU will be established as a comparative to isolate the difference. The outcome variable I will be tracking is liberalism, as quantified by the UN's Human Freedom Index. This is an annual evaluation of how free a given country is. I expect that over time most of these countries will have trended towards becoming more liberal, but a difference-in-difference analysis will reveal whether the explanatory had some additional effect. If the difference-in-difference analysis indicates a higher rate of liberalization in member countries vs non-member countries, this will suggest that time spent within the EU is positively related to liberalization, proving the hypothesis correct. No difference or a negative relationship would disprove the hypothesis. 
